products/config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :manufacturers
  
  resources :products
end

products/app/models/manufacturer.rb
class Manufacturer < ApplicationRecord
     #plural because many students, relationships stored in ruby, creates ruby methods
   has_many :products
end

products/app/models/product.rb
class Product < ApplicationRecord
     #child of course, student only in one class at a time 
    belongs_to :manufacturer
end

products/app/controllers/manufacturers_controller.rb
class ManufacturersController < ApplicationController
    def index
        @manufacturers = Manufacturer.all
    end
    
    def new
        @manufacturer = Manufacturer.new
    end
     
    def create
        manufacturer= Manufacturer.new
        manufacturer.name = params[:manufacturer][:name]
        manufacturer.city = params[:manufacturer][:city]
        manufacturer.state = params[:manufacturer][:state]
        manufacturer.zip = params[:manufacturer][:zip]
        manufacturer.country = params[:manufacturer][:country]
        manufacturer.manufacturer_type = params[:manufacturer][:manufacturer_type]
        manufacturer.save
        redirect_to '/manufacturers'
    end
    
    def edit
       @manufacturer = Manufacturer.find(params[:id])
    end
    
    def show
        #needs work
        @manufacturer = Manufacturer.find(params[:id])
    end
    
    def update
        manufacturer = Manufacturer.find(params[:id])
        manufacturer.name = params[:manufacturer][:name]
        manufacturer.city = params[:manufacturer][:city]
        manufacturer.state = params[:manufacturer][:state]
        manufacturer.zip = params[:manufacturer][:zip]
        manufacturer.country = params[:manufacturer][:country]
        manufacturer.manufacturer_type = params[:manufacturer][:manufacturer_type]
        manufacturer.save
        redirect_to '/manufacturers'
    end
    
    def destroy
        #needs work
        manufacturer =Manufacturer.find(params[:id])
        manufacturer.destroy
        redirect_to '/manufacturers'
    end
    
end

products/app/controllers/products_controller.rb
class ProductsController < ApplicationController
    def index
        @products = Product.all
    end
    
    def new
        @product = Product.new
        @manufacturers =Manufacturer.all
    end
     
    def create
        product= Product.new
        product.item_name = params[:product][:item_name]
        product.item_description = params[:product][:item_description]
        product.item_picture = params[:product][:item_picture]
        product.manufacturer_id= params[:product][:manufacturer_id]
        product.save
        redirect_to '/products'
    end
    
    def edit
       @product = Product.find(params[:id])
    end
    
    
    def update
        product = Product.find(params[:id])
        product.name = params[:product][:name]
        product.city = params[:product][:city]
        product.state = params[:product][:state]
        product.zip = params[:product][:zip]
        product.country = params[:product][:country]
        product.product_type = params[:product][:product_type]
        product.save
        redirect_to '/products'
    end
    
    def destroy
        #needs work
        product =Product.find(params[:id])
        product.destroy
        redirect_to '/products'
    end
end

products/app/helpers/manufacturers_helper.rb
module ManufacturersHelper
end

products/app/helpers/products_helper.rb
module ProductsHelper
end

products/app/views/manufacturers/edit.html.erb
<%= form_for @manufacturer do |f| %>
    <div>
        <%= f.text_field :name, placeholder: 'Name'%>
    </div>
    <div>
        <%= f.text_field :city, placeholder: 'City'%>
    </div>
    <div>
        <%= f.text_field :state, placeholder: 'State'%>
    </div>
    <div>
        <%= f.text_field :zip, placeholder: 'ZIP'%>
    </div>
    <div>
        <%= f.text_field :country, placeholder: 'Country'%>
    </div>
    <div>
        <%= f.text_field :manufacturer_type, placeholder: 'Type of Manufacturer'%>
    </div> 
    <div>
        <%= f.submit 'Save'%>
    </div> 
    
<%end%>

products/app/views/manufacturers/index.html.erb
<%= link_to 'New',new_manufacturer_path %>

<% @manufacturers.each do |manufacturer|%>
    
    <h4> <%=manufacturer.name%></h4>
    <%= manufacturer.city%>
    <%= manufacturer.state%>
    <%= manufacturer.zip%>
    <%= manufacturer.country%>
    <%= manufacturer.manufacturer_type%>  
    <%= link_to 'Edit',edit_manufacturer_path(manufacturer.id) %>
    <!-- prevent deletion if it has products still in database -->
    <!-- needs to be able to not look like link-->
    <%= link_to_unless !manufacturer.products.empty?, 'Destroy', manufacturer_path(manufacturer.id),
              method: :delete,
              data: { confirm: 'Are you sure?' } do link_to('cannot delete')end %>
               <%= link_to 'Show', manufacturer_path(manufacturer.id),
              method: :get,
              data: { confirm: 'Are you sure?' } %>
   
<% end %>

products/app/views/manufacturers/new.html.erb
<%= form_for @manufacturer do |f| %>
    <div>
        <%= f.text_field :name, placeholder: 'Name'%>
    </div>
    <div>
        <%= f.text_field :city, placeholder: 'City'%>
    </div>
    <div>
        <%= f.text_field :state, placeholder: 'State'%>
    </div>
    <div>
        <%= f.text_field :zip, placeholder: 'ZIP'%>
    </div>
    <div>
        <%= f.text_field :country, placeholder: 'Country'%>
    </div>
    <div>
        <%= f.text_field :manufacturer_type, placeholder: 'Type of Manufacturer'%>
    </div> 
    <div>
        <%= f.submit 'Save'%>
    </div> 
    
<%end%>

products/app/views/manufacturers/show.html.erb
<h1><%=@manufacturer.name%></h1>

<h5>Products</h5>

<%@manufacturer.products.each do |product| %>
<div>
    <%=product.item_name%> <%=product.item_description%><%=product.item_picture%>
</div>
<%end%>