games/config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  #when this route is farther down in the list rails assumes i want a destroy method even with the specific class path players_remove_game_path. 
  #It assumes I want the regular destroy method for player_path havent figured out why
  
  
  resources :games
  resources :players
  delete '/game/remove_player' => 'games#delete_player'
  delete '/player/remove_game' => 'players#delete_game'
  post '/player/add_game' => "players#add_game"
  root "players#index"
end

games/app/models/game.rb
class Game < ApplicationRecord
    has_many :player_games
    has_many :players, through: :player_games
end

games/app/models/player.rb
class Player < ApplicationRecord
    has_many :player_games
    has_many :games, through: :player_games
end

games/app/models/player_game.rb
class PlayerGame < ApplicationRecord
    belongs_to :player
    belongs_to :game
end

games/app/controllers/games_controller.rb
class GamesController < ApplicationController
    def index
        @games = Game.all
    end
    def new
        @game =Game.new
    end
    def create
        game =Game.new
        game.name=params[:game][:name]
        game.genre=params[:game][:genre]
        game.description=params[:game][:description]
        game.publisher=params[:game][:publisher]
        game.save
        redirect_to games_path
    end
    def edit
         @game =Game.find(params[:id])
    end
    def update
        game =Game.find(params[:id])
        game.name=params[:game][:name]
        game.genre=params[:game][:genre]
        game.description=params[:game][:description]
        game.publisher=params[:game][:publisher]
        game.save
        redirect_to games_path
    end
    def show
        @game = Game.find(params[:id])
        @players=Player.all
    end
    
    def delete_player
        game =Game.find(params[:game_id])
        player_games =PlayerGame.where(
            player_id: params[:player_id],
            game_id: params[:game_id]
            )
            player_games.each do |player_game|
                player_game.destroy
            end
            
        redirect_to game_path(game)
            
        
    end
    
end

games/app/controllers/players_controller.rb
class PlayersController < ApplicationController
    def index
        @players = Player.all
    end
    def new
        @player =Player.new
    end
    def create
        player =Player.new
        player.gamerTag=params[:player][:gamerTag]
        player.first_name=params[:player][:first_name]
        player.last_name=params[:player][:last_name]
        player.avatar=params[:player][:avatar]
        player.save
        redirect_to players_path
    end
    def edit
         @player =Player.find(params[:id])
    end
    def update
        player =Player.find(params[:id])
        player.gamerTag=params[:player][:gamerTag]
        player.first_name=params[:player][:first_name]
        player.last_name=params[:player][:last_name]
        player.avatar=params[:player][:avatar]
        player.save
        redirect_to players_path
    end
    def show
        @player = Player.find(params[:id])
        @games=Game.all
    end
    
    def add_game
        player =Player.find(params[:player_id])
        player_game =PlayerGame.find_by(
            player_id: params[:player_id],
            game_id: params[:game_id])
        if player_game==nil
          
            player_game = PlayerGame.new
            player_game.player_id = params[:player_id]
            player_game.game_id = params[:game_id]
            player_game.save
        end
        redirect_to player_path(player)
        
        
    end
    def destroy
        player_games =PlayerGame.where( player_id: params[:id])
        player_games.each do |delete|
            delete.destroy
        end
        player =Player.find(params[:id])
       
        player.destroy
        redirect_to players_path
    
    end
    
   
    
    def delete_game
        player =Player.find(params[:player_id])
        player_games =PlayerGame.where(
            player_id: params[:player_id],
            game_id: params[:game_id]
            )
            player_games.each do |player_game|
                player_game.destroy
            end
            
        redirect_to player_path(player)
            
        
    end
end

games/app/helpers/games_helper.rb
module GamesHelper
end

games/app/helpers/players_helper.rb
module PlayersHelper
end

games/app/views/games/edit.html.erb
<%=form_for @game do |f|%>
<div>
    <%=f.text_field :name ,placeholder:"Name"%> 
</div>
    <div>
          <%=f.text_field :genre ,placeholder:"Genre"%> 
    </div>
    
    <div>
        <%=f.text_area :description ,placeholder:"Description"%> 
    </div>
    
    <div>
        <%=f.text_field :publisher ,placeholder:"Publisher"%> 
    </div>
  
     <div>
        <%=f.submit "Save"%>
    </div>

<%end%>

games/app/views/games/index.html.erb
<%=link_to "New", new_game_path%>

<% @games.each do |game|%>
<div>
    <h1><%=game.name%></h1>
    <p><%=game.genre%> </p>
    <p>
        <%=game.description%>
    </p>
    <h5>
        <%=game.publisher%>
    </h5>
</div>
<%= link_to "Edit",edit_game_path(game.id)%>
<%= link_to "Show",game_path(game.id)%>

<%end%>

games/app/views/games/new.html.erb
<%=form_for @game do |f|%>
<div>
    <%=f.text_field :name ,placeholder:"Name"%> 
</div>
    <div>
          <%=f.text_field :genre ,placeholder:"Genre"%> 
    </div>
    
    <div>
        <%=f.text_area :description ,placeholder:"Description"%> 
    </div>
    
    <div>
        <%=f.text_field :publisher ,placeholder:"Publisher"%> 
    </div>
  
     <div>
        <%=f.submit "Save"%>
    </div>

<%end%>

games/app/views/games/show.html.erb
<h1><%=@game.name%></h1>

<h2>Played By: </h2>
    
    <% @game.players.each do |player|%>
    <div>
        <h5><%=player.gamerTag%></h5>
        <p><%=player.first_name%></p>
        
    </div>
    <%= link_to 'Delete', game_remove_player_path(game_id: @game.id, player_id: player.id), method: :delete%>
    
    <%end%>

games/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Games</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
     <link href="https://stackpath.bootstrapcdn.com/bootstrap/4.2.1/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-GJzZqFGwb1QTTN6wy59ffF1BuGJpLSa9DkKMp0DgiMDm4iYMj70gZWKYbI706tWS" crossorigin="anonymous">
    <%= link_to 'Games', games_path%>
    <%= link_to 'Players', players_path%>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>