Restaurant/config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :dishes
  resources :orders do
    member do
      get 'prepare'
      post 'add'
      delete 'remove'
      put 'submit'
    end
  end
   
  get '/restaurant/orders' => 'restaurant_orders#index'
  put '/restaurant/orders/:id/prepare' => 'restaurant_orders#prepare', as: :prepare
  put '/restaurant/orders/:id/entroute' => 'restaurant_orders#enroute', as: :enroute
  put '/restaurant/orders/:id/deliver' => 'restaurant_orders#deliver', as: :deliver
  put '/restaurant/orders/:id/completed' => 'restaurant_orders#complete', as: :complete
   
 
  root 'orders#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

Restaurant/app/models/dish.rb
class Dish < ApplicationRecord
    has_many :order_dishes
    has_many :orders, through: :order_dishes
    
    validates :name, presence: true, uniqueness: true
end

Restaurant/app/models/order.rb
class Order < ApplicationRecord
    belongs_to :user
    has_many :order_dishes
    has_many :dishes, through: :order_dishes
    
    def total
        total=0
        dishes.each do |dish|
            total = total + dish.price
        end
        return total.round(2)
    end
    
end

Restaurant/app/models/order_dish.rb
class OrderDish < ApplicationRecord
    belongs_to :order
    belongs_to :dish
end

Restaurant/app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
         has_many :orders
end

Restaurant/app/controllers/dishes_controller.rb
class DishesController < ApplicationController
    def index
        @dishes = Dish.all
    end
    
    def new
        @dish = Dish.new
    end
    
    def create
         dish = Dish.new
         dish.name = params[:dish][:name]
         dish.description =params[:dish][:description]
         dish.picture=params[:dish][:picture]
         dish.price=params[:dish][:price]
         dish.save
         redirect_to dishes_path
    end
    
    def edit
        
        @dish =Dish.find(params[:id])
    end
    
    def update
        @dish =Dish.find(params[:id])
        @dish.name = params[:dish][:name]
        @dish.description =params[:dish][:description]
        @dish.picture=params[:dish][:picture]
        @dish.price=params[:dish][:price]
        if @dish.save
            redirect_to dishes_path
        else
           render 'edit' 
           flash[:error] = @dish.errors
        end
    end
    
    def delete
        dish = Dish.find(params[:id])
        dish.destroy
    end

end

Restaurant/app/controllers/orders_controller.rb
class OrdersController < ApplicationController
    before_action :authenticate_user!
    
    def index
        @orders = Order.where(user_id: current_user.id)
    end
    
    def show
    end
    
    def new
        @order =Order.new
    end
    
    def create
        @order =Order.new
        @order.street_address =params[:order][:street_address]
        @order.city =params[:order][:city]
        @order.state =params[:order][:state]
        @order.zip =params[:order][:zip]
        @order.status ='Created'
        @order.user_id = current_user.id
        @order.save
        redirect_to prepare_order_path(@order)
    end
    
    def prepare
        @order =Order.find(params[:id])
        @dishes=Dish.all
        @total= 0
        #Summing prices of all dishes in order
        @order.dishes.each do |dish|
            @total= @total + dish.price
        end
        @total =@total.round(2)
    end
    
    def add
        @order = Order.find(params[:id])
       order_dish = OrderDish.new
       order_dish.dish_id = params[:dish_id]
       order_dish.order_id = params[:id]
       order_dish.save
       redirect_to prepare_order_path(@order)
    end
    
    def remove
        @order = Order.find(params[:id])
        order_dish = OrderDish.find(params[:order_dish_id])
        order_dish.destroy
        redirect_to prepare_order_path(@order)
    end
    
    def submit
        @order = Order.find(params[:id])
        @order.status ="Submitted"
        @order.save
        redirect_to orders_path
    end
    
end

Restaurant/app/controllers/restaurant_orders_controller.rb
class RestaurantOrdersController < ApplicationController
    def index
        @orders = Order.where(status: ['Submitted','Preparing','Enroute','Delivering'])
    end
    def prepare
        @order = Order.find(params[:id])
        @order.status ="Preparing"
        @order.save
        redirect_to restaurant_orders_path
        
    end
    def enroute
        @order = Order.find(params[:id])
        @order.status ="Enroute"
        @order.save
        redirect_to restaurant_orders_path
        
    end
    def deliver
        @order = Order.find(params[:id])
        @order.status ="Delivering"
        @order.save
        redirect_to restaurant_orders_path
        
    end
    def complete
        @order = Order.find(params[:id])
        @order.status ="Complete"
        @order.save
        redirect_to restaurant_orders_path
    end
end

Restaurant/app/helpers/dishes_helper.rb
module DishesHelper
end

Restaurant/app/helpers/orders_helper.rb
module OrdersHelper
end

Restaurant/app/helpers/restaurant_orders_helper.rb
module RestaurantOrdersHelper
end

Restaurant/app/views/orders/index.html.erb
<%=link_to 'New Order',new_order_path%>

<% @orders.each do |order| %>
    <div>
        <%=order.street_address%>
        <%=order.city%>
        <%=order.state%>
        <%=order.zip%>
        <%=order.status%>
    </div>
<%end%>

Restaurant/app/views/orders/new.html.erb
<!-- try some Styling and include timestamp info -->
<%= form_for @order do |f| %>
    
    <div>
        <%=f.text_field :street_address ,placeholder:"Street Address"%> 
    </div>
  
    <div>
        <%=f.text_field :city ,placeholder:"City"%> 
    </div>
    
    <div>
        <%=f.text_field :state ,placeholder:"State"%> 
    </div>
    <div>
        <%=f.text_field :zip ,placeholder:"ZIP"%> 
    </div>
 
     <div>
        <%=f.submit "Create"%>
    </div>
    
    <%end%>

Restaurant/app/views/orders/prepare.html.erb
<div class="row">
    <div class="col-8">
        <h2>Menu</h2>
            <% @dishes.each do |dish| %>
              <div class="card" style="width: 18rem;">
                <%=image_tag dish.picture,height: 100%>
            <div class="card-body">
               <h4><%=dish.name%></h4>
               <p> <%=dish.description%></p>
               
                <p>$<%=dish.price%></p>
                    
                    <%=link_to 'Add ',add_order_path(@order,dish_id: dish.id), method: :post, class: "btn btn-primary"%>
                </div>
    </div>



<%end%>
    </div>



    <div class="col-4">
        <!-- Used card css from bootstrap before lesson started and liked the look used media object in lesson-->
        <h4>Order:</h4>
        <h5><%= @order.order_dishes.length %> items</h5>
        <% @order.order_dishes.each do |order_dish| %>
        <div>
            <div class="card" style="width: 18rem;">
                 <%=image_tag order_dish.dish.picture,height: 100%>
                <div class="card-body">
                   <h4><%=order_dish.dish.name%></h4>
                   
                   
                    <p>$<%=order_dish.dish.price %></p>
                    
                    <%=link_to 'Remove ', remove_order_path(@order,order_dish_id: order_dish.id), method: :delete, class: "btn btn-danger"%>
                </div>
                
            </div>
        <%end%>
        <h6>Total: $<%=@total%></h6>
        <%=link_to 'Submit', submit_order_path(@order), method: :put,class: "btn btn-success"%>
    </div>
</div>

Restaurant/app/views/restaurant_orders/index.html.erb
<%@orders.each do |order|%>
    <div class="row">
        <div class="col-2">
            <%=order.status%>
        </div>
        <div class="col-6">
            <%= order.street_address%>
            <%= order.city%>
            <%= order.state%>
             <%= order.zip%>
               </div>
        <div class="col-2">
            $<%= order.total %>
        </div>
     
        <div class="col-2">
            <%if order.status =='Submitted'%>
            <%=link_to 'Prepare',prepare_path(order),method: :put,class:'btn btn-sm btn-secondary mb-2' %>
            <% elsif order.status =="Preparing"%>
            <%=link_to 'Enroute',enroute_path(order),method: :put,class:'btn btn-sm btn-secondary mb-2' %>
            <% elsif order.status =="Enroute"%>
            <%=link_to 'Deliver',deliver_path(order),method: :put,class:'btn btn-sm btn-secondary mb-2' %>
            <% elsif order.status =="Delivering"%>
            <%=link_to 'Complete',complete_path(order),method: :put,class:'btn btn-sm btn-secondary mb-2' %>
            <%end%>
        </div>
    </div>
    <% if order.status == 'Preparing'%>
        <% order.order_dishes.each do |order_dish|%>
        
            
              <div class="card" style="width: 8em;">
                     <%=image_tag order_dish.dish.picture,height: 50%>
                    <div class="card-body">
                       <h4><%=order_dish.dish.name%></h4>
                        
                    </div>
                    
                </div>
        
        <%end%>
    <%end%>
<%end%>